### ISSUE TITLE
ApexCharts broken since Vaadin version 23.2.0

### ISSUE THREAD

**Issue by klauss42** [appreciated/apexcharts-flow#140]
**Describe the bug**
After upgrading from Vaadin flow 23.1.7 to 23.2.0 the charts implemented with ApexCharts v2.0.0-beta13 are not working anymore.

The following error is shown in the JS console in Chrome:
```
Uncaught ReferenceError: require is not defined
    at ApexChartsWrapper.ready (generated-flow-imports.ad03bda7.js:7529:622)
    at E.ready (FlowClient.947c8d40.js:3:77663)
    at ApexChartsWrapper._enableProperties (generated-flow-imports.ad03bda7.js:193:2486)
    at ApexChartsWrapper.connectedCallback (generated-flow-imports.ad03bda7.js:235:1559)
    at ApexChartsWrapper.connectedCallback (generated-flow-imports.ad03bda7.js:245:5028)
````

We are using different chart types, at least sparkline and donut were not working anymore.
Downgrading to Vaadin 23.1.7 fixed the issue.

**Expected behavior**
ApexCharts should work after upgrading to Vaadin 23.2.0

**Desktop (please complete the following information):**
 - OS: Mac and Windows
 - Browser: chrome
 - Version: 2.0.0-beta12 

**Smartphone (please complete the following information):**

**Comment by mrgreywater** [comment]
Will be resolved once https://github.com/appreciated/apexcharts-flow/pull/134 is merged.

**Comment by TFyre** [comment]
Please test with #141

If it works, we can wait for #134 to fix the merge conflict and merge both
