### ISSUE TITLE
Support for the upcoming Vaadin 14.2.x 

### ISSUE THREAD

**Issue by markhm** [appreciated/apexcharts-flow#63]
Just tested with pre-release Vaadin 14.2.0.alpha10 to benefit from the reduced memory footprint this version will offer, but I noticed that ApexCharts-Flow does not support 14.2.x yet.

It would be wonderful if 14.2.x could be supported right when it becomes available, expected April 2020. 

```
Caused by: java.lang.IllegalStateException: Couldn't find the definition of the element with tag 'apex-charts-wrapper' in any template file declared using '@JsModule' annotations. Check the availability of the template files in your WAR file or provide alternative implementation of the method getTemplateContent() which should return an element representing the content of the template file
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:143)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at com.github.appreciated.apexcharts.ApexCharts.<init>(ApexCharts.java:26)
	at com.github.appreciated.apexcharts.ApexChartsBuilder.build(ApexChartsBuilder.java:176)
```

**Comment by appreciated** [comment]
[I guess this is also related to the issue that I opened on vaadin-flow](https://github.com/vaadin/flow/issues/7752)

**Comment by markhm** [comment]
Thank you for this reference. 

I have tried with v15.0.4 (which should contain a fix) and v14.2.0.alpha10 while patching flow, but unfortunately, this did not resolve the problem.

**Comment by appreciated** [comment]
I not sure if you can simply patch 14.2.* with 15.* 🙈.  
Could you provide more information about your setup? [I guess you have already tried reinstalling the npm dependencies](https://github.com/appreciated/apexcharts-flow/issues/51#issuecomment-599956093).

**Comment by markhm** [comment]
I just got apexcharts-flow to work under a clean v15.0.4 application (https://vaadin.com/start/latest, Vaadin 15 (Latest), Simple App), will now a more complex example with Spring Boot and try to present a failing demo.

**Comment by markhm** [comment]
I was unable to upgrade my existing workspace to v15, so I've started with a new workspace and migrated my solution. It does not contain AppLayout yet, but basic functionality is working again. Fingers crossed, so closing this for now. Thank you for your support.
